<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($images = $this->getImages()): ?>
    <style type="text/css">
        #gallery-<?= $this->getGalleryIt() ?> {margin: auto;}
        #gallery-<?= $this->getGalleryIt() ?> .gallery-item {float: left;margin-top: 10px;text-align: center;width: <?= floor(100 / $this->getColumns()) ?>%;}
        #gallery-<?= $this->getGalleryIt() ?> img {border: 2px solid #cfcfcf;}
        #gallery-<?= $this->getGalleryIt() ?> .gallery-caption {margin-left: 0;padding-left:0;}    
    </style>
    <?php $columns = $this->getColumns() ?>
    <?php $imageCount = count($images) ?>
    <div class="gallery galleryid-<?= $this->getObject()->getId() ?> gallery-columns-<?= $this->getColumns() ?> gallery-size-<?= $this->getSize() ?> gallery<?= $this->getGalleryIt() ?>" id="gallery-<?= $this->getGalleryIt() ?>">
        <?php $it = 0; foreach ($images as $image): ?>
        <dl class="gallery-item"<?php if ($it%$columns == 0): ?> style="clear: left;"<?php endif; ?>>
            <dt class="gallery-icon">
                <a title="<?= $this->escapeHtml($image->getPostTitle()) ?>" rel="gallery<?= $this->getGalleryIt() ?>" href="<?= $image->getFullSizeImage() ?>"><img title="<?= $image->getPostTitle() ?>" alt="<?= $image->getPostTitle() ?>" class="attachment-<?= $this->getSize() ?>" src="<?= $image->getImageByType($this->getSize()) ? $image->getImageByType($this->getSize()) : $image->getAvailableImage() ?>" /></a>
            </dt>
            <?php if (($caption = trim($this->stripTags($image->getPostExcerpt()))) !== false): ?>
                <dd class="wp-caption-text gallery-caption"><?= $caption ?></dd>
            <?php endif; ?>
        </dl>
            <?php ++$it;
endforeach; ?>
    </div>
    <div class="clearer"></div>
<?php endif; ?>