<?php
/*
 * @requires FishPig_WordPress_PluginShortcodeWidget
 * @url      https://fishpig.co.uk/magento/wordpress-integration/shortcodes-widgets/
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output') ?>
<?php $_products = $this->getProductCollection() ?>
<?php if (count($_products) > 0): ?>
	<div class="shortcode-product">
		<ol class="products">
		<?php foreach($_products as $_product): ?>
			<li>
				<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo">
					<?php echo $this->getImage($_product, 'category_page_list')->toHtml() ?>
				</a> 
				<strong class="product name product-item-name">
					<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
				</strong>
                <?php #echo $block->getReviewsSummaryHtml($_product) ?>
				<?php echo $block->getProductPrice($_product) ?>
                <?php #echo $block->getProductSwatchHtml($_product) ?>
			</li>
		<?php endforeach; ?>
		</ol>
	</div>
<?php endif; ?>