<?php
/**
 *
 **/
?>
<?php if ($post = $block->getPost()): ?>
    <?php if ($image = $post->getImage()): ?>
        <div class="post-image">
            <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getPostTitle()) ?>"><img src="<?= $image->getAvailableImage() ?>" alt="<?= $block->escapeHtml($post->getPostTitle()) ?>"/></a>
        </div>
    <?php endif; ?>
<?php endif; ?>