<?php
/**
 *
 **/
?>
<?php if ($post = $block->getPost()): ?>
    <?php if ((int)$block->getHeadingLevel() === 1): ?>
        <h1 class="post-name"><?= $block->escapeHtml($post->getName()) ?></h1>
    <?php else: ?>
        <h<?= (int)$block->getHeadingLevel() ?> class="post-name">
            <a href="<?= $post->getUrl() ?>" title="<?= $block->escapeHtml($post->getName()) ?>">
                <?= $block->escapeHtml($post->getName()) ?>
            </a>
        </h<?= (int)$block->getHeadingLevel() ?>>
    <?php endif; ?>
<?php endif; ?>