<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $block->getPost() ?>
<?php $comments = $block->getComments() ?>
<div id="comments" class="comments-wrapper">
    <?php if (count($comments) > 0): ?>
        <?php if ($block->getCommentCount() == 1): ?>
            <h2><?= $block->escapeHtml(__('1 Comment')) ?></h2>
        <?php else: ?>
            <h2><?= $block->escapeHtml(__('%1 Comments', (int)$block->getCommentCount())) ?></h2>
        <?php endif; ?>
        <?= $block->getCommentsHtml() ?>
        <?= $block->getPagerHtml() ?>
    <?php endif; ?>
    <?= $block->getFormHtml() ?>
</div>
