<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($tags = $this->getTags()): ?>
	<?php $tagCount = count($tags) ?>
	<div class="block block-blog block-blog-cloud">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><?php echo __($title) ?></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul class="tags-list">
				<?php foreach ($tags as $tag): ?>
					<li<?php if (--$tagCount < 1): ?> class="last"<?php endif; ?>><a href="<?php echo $tag->getUrl() ?>" style="font-size:<?php echo $this->getFontSize($tag) ?>%;"><?php echo $this->escapeHtml($tag->getName()) ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>