<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
// phpcs:ignoreFile -- long lines (todo)
?>
<?php if ($tags = $block->getTags()): ?>
    <?php $tagCount = count($tags) ?>
    <div class="block block-blog block-blog-cloud">
        <?php if ($title = $block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($title)) ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <ul class="tags-list">
                <?php foreach ($tags as $tag): ?>
                    <li<?php if (--$tagCount < 1): ?> class="last"<?php endif; ?>><a href="<?= $block->escapeUrl($tag->getUrl()) ?>" style="font-size:<?= $block->escapeHtml($block->getFontSize($tag)) ?>%;"><?= $block->escapeHtml($tag->getName()) ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>