<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($content = $this->getContent()): ?>
<div class="block block-blog block-blog-custom-html">
	<?php if ($title = $this->getTitle()): ?>
		<div class="block-title">
			<strong><?php echo __($title) ?></strong>
		</div>
	<?php endif; ?>
	<div class="block-content"><?php echo $content ?></div>
</div>
<?php endif; ?>