<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($content = $block->getContent()): ?>
<div class="block block-blog block-blog-custom-html">
    <?php if ($title = $block->getTitle()): ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($title)) ?></strong>
        </div>
    <?php endif; ?>
    <div class="block-content"><?= /* @noEscape */ $content ?></div>
</div>
<?php endif; ?>