<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
// phpcs:ignoreFile -- long lines (todo)
?>
<div class="block block-blog block-blog-meta">
    <div class="block-title">
        <strong><span><?= $block->escapeHtml(__($block->getTitle())) ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="wp-meta-list">
            <li class="item">
                <a href="https://fishpig.co.uk/magento/wordpress-integration/" title="Magento WordPress Integration"><span>Magento WordPress Integration</span></a>
            </li>
            <li class="item">
                <a href="https://fishpig.co.uk/magento/extensions/" title="Magento Extensions"><span>Magento Extensions</span></a>
            </li>
        </ul>
    </div>
</div>