<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="block block-blog block-blog-meta">
	<div class="block-title">
		<strong><span><?php echo __($this->getTitle()) ?></span></strong>
	</div>
	<div class="block-content">
		<ul id="wp-meta-list">
			<li class="item">
				<a href="https://fishpig.co.uk/magento/wordpress-integration/" title="<?php echo __('Magento WordPress Integration') ?>"><span><?php echo __('Magento WordPress Integration') ?></span></a>
			</li>
			<li class="item">
				<a href="https://fishpig.co.uk/magento/extensions/" title="<?php echo __('Magento Extensions') ?>"><span><?php echo __('Magento Extensions') ?></span></a>
			</li>
			<li class="item">
				<a href="http://wordpress.org/" title="<?php echo __('Powered by WordPress, state-of-the-art semantic personal publishing platform.') ?>"><span><?php echo __('WordPress.org') ?></span></a>
			</li>
			<li class="item">
				<a href="http://www.magentocommerce.com/" title="<?php echo __('Magento eCommerce') ?>"><span><?php echo __('Magento') ?></span></a>
			</li>
		</ul>
	</div>
</div>