<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($this->getMenu()): ?>
	<?php $tree = [$this->getMenu()->getMenuTreeArray()] ?>
	<?php if (count($tree) > 0): ?>
		<div class="block block-blog block-blog-nav-menu">
			<?php if ($title = $this->getTitle()): ?>
				<div class="block-title">
					<strong><?php echo $this->escapeHtml($title) ?></strong>
				</div>
			<?php endif; ?>
			<div class="block-content">
				<ul id="wp-page-list">
	<?php echo $this->getTreeHtml(); ?>
				</ul>
			</div>
		</div>
	<?php endif; ?>
<?php endif; ?>