<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
// phpcs:ignoreFile -- long lines (todo)
?>
<?php $pages = $block->getPages() ?>
<?php if (count($pages) > 0): ?>
    <div class="block block-blog block-blog-pages">
        <?php if ($title = $block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($title)) ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <ul id="wp-page-list">
                <?php foreach ($pages as $page): ?>
                    <li class="item">
                        <a href="<?= $block->escapeUrl($page->getUrl()) ?>" title="<?= $block->escapeHtml($page->getPostTitle()) ?>"><?= $block->escapeHtml($page->getPostTitle()) ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>