<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
// phpcs:ignoreFile -- long lines (todo)
?>
<?php $posts = $block->getPosts() ?>
<?php if (count($posts) > 0): ?>
    <div class="block block-blog block-recent-posts">
        <?php if ($title = $block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($title)) ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <ul id="<?= $block->escapeHtmlAttr($block->getListId()) ?>">
            <?php foreach ($posts as $post): ?>
                <li class="item">
                    <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getPostTitle()) ?>"><?= $block->escapeHtml($post->getPostTitle()) ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>