<?php
/*
 *
 */
?>
<?php
/*
 * If you are using custom post types, you can create a custom render for the post type easily
 * Simply create a file using the name of the custom post type in this folder (in your custom theme)
 * For example, if your custom post type is 'news_article', you would create a file named news_article.phtml
 * This file would live in the templates/post/list/renderer/news_article.phtml in your custom theme
 */
?>