<?php
/** @var \FishPig\WordPress\Block\Adminhtml\Catalog\Product\Edit\PostAssociation $block */
$blockGrid = $block->getBlockGrid();
/** @var \FishPig\WordPress\Block\Adminhtml\Catalog\Product\Edit\Tab\PostAssociation $blockGrid */
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="product_posts" id="in_product_posts" data-form-part="product_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "FishPig_WordPress/js/catalog/product/associated-posts": {
                "selectedPosts": <?= /* @escapeNotVerified */ $block->getPostsJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
