<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $block->getPosts() ?>
<?php if (count($posts) > 0): ?>
    <div class="post-list-wrapper">
        <ol class="post-list grid">
            <?php foreach ($posts as $post): ?>
                <?php if ($renderedPostHtml = $block->renderPost($post)): ?>
                    <li class="item<?php if ($post->isSticky()): ?> featured is-sticky<?php endif; ?> <?= $block->escapeHtml($post->getPostFormat()) ?>">
                        <?= $renderedPostHtml ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
        <?= $block->getPagerHtml() ?>
    </div>
<?php endif; ?>