<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $block->getPosts() ?>
<?php if (count($posts) > 0): ?>
    <div class="post-list-wrapper">
        <ol class="post-list grid">
            <?php foreach ($posts as $post): ?>
                <?php if ($renderedPostHtml = $block->renderPost($post)): ?>
                    <?php // phpcs:ignore -- long line ?>
                    <li class="item<?= $post->isSticky() ? 'featured is-sticky' : '' ?> <?= $block->escapeHtmlAttr($post->getPostFormat()) ?>">
                        <?= /* @noEscape */ $renderedPostHtml ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
        <?= /* @noEscape */  $block->getPagerHtml() ?>
    </div>
<?php endif; ?>