<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($post = $block->getPost()): ?>
    <?php if (!$post->isViewableForVisitor()): ?>
        <?= $block->getPasswordProtectHtml() ?>
    <?php else: ?>
        <div class="post-view">
            <div class="post-entry">
                <?php if ($image = $post->getImage()): ?>
                    <?php $imageUrl =  $image->getResizer() ? $image->getResizer()->constrainOnly(true)->keepFrame(false)->keepAspectRatio(true)->resize(1200, null) : ''?>
                    <div class="post-image">
                        <a href="<?= $block->escapeUrl($post->getUrl()) ?>" title="<?= $block->escapeHtml($post->getPostTitle()) ?>"><img src="<?= $imageUrl ?>" alt="<?= $block->escapeHtml($post->getPostTitle()) ?>"/></a>
                    </div>
                <?php endif; ?>
                <?php if (($content = trim($post->getContent())) !== ''): ?>
                    <div class="post-content"><?= $content ?></div>
                <?php endif; ?>
            </div>
            <div class="post-meta">
                <?php if ($categoryString = $post->getTermCollectionAsString('category')): ?>
                    <div class="post-categories post-meta-item">
                        <strong><?= __('Categories') ?>:</strong> <?= $categoryString ?>
                    </div>
                <?php endif; ?>
                <?php if ($tagString = $post->getTermCollectionAsString('post_tag')): ?>
                    <div class="post-tags post-meta-item">
                        <strong><?= __('Tags') ?>:</strong> <?= $tagString ?>
                    </div>
                <?php endif; ?>
                <div class="post-date post-meta-item">
                    <strong><?= __('Posted On') ?>:</strong> <?= $post->getPostDate() ?>
                </div>
                <div class="post-user post-meta-item">
                    <strong><?= __('Posted By') ?>:</strong> <a href="<?= $block->escapeUrl($post->getUser()->getUrl()) ?>"><?= $block->escapeHtml($post->getUser()->getDisplayName()) ?></a>
                </div>
            </div>
            <?= $block->getChildHtml('comments') ?>
        <?php endif; ?>
    </div>
<?php endif; ?>