<?php
/**
 *
 */
// phpcs:ignoreFile
?>
<p>Securely login to your WordPress Admin with a single click using the <a href="<?= $block->getExtensionUrl() ?>" target="_blank">Auto Login add-on module</a> for Magento 2.</p>
<p style="margin-top: 40px;"><button type="button" class="button primary action" onclick="window.open('<?= $block->escapeUrl($block->getExtensionUrl()) ?>')"><span>View the AutoLogin Module</span></button></p>