<?php
/**
 *
 */
// phpcs:ignoreFile -- long lines
?>
<?php if ($msgs = $block->getMessages()): ?>
    <div class="messages">
        <?php foreach ($msgs as $msg): ?>
            <div class="message message-<?= $block->escapeHtmlAttr($msg['type']) ?> <?= $block->escapeHtmlAttr($msg['type']) ?>">
                <div><?= $block->escapeHtml($msg['msg'], ['a', 'span', 'br']) ?></div>
            </div>
        <?php endforeach; ?>
    </div>
    <?= $block->getAfterMessagesHtml() ?>
<?php endif; ?>