<?php
/**
 * @category    FishPig
 * @package     FishPig_WordPress
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php if ($text = $block->getDescription()): ?>
    <p class="post-list-description"><?= $block->escapeHtml($text) ?></p>
<?php endif; ?>
<?php if ($postList = trim($block->getPostListHtml())): ?>
    <?= /* @noEscape */ $postList ?>
<?php else: ?>
    <p class="note-msg"><?= $block->escapeHtml(__('There are no posts matching your selection.')) ?></p>
<?php endif; ?>